name: check code
on:
  workflow_dispatch:
  commit: 
    branches:
      - main

jobs: 
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3